version: "3.8"

services:
  # NATS Servers (Cluster)
  nats-1:
    image: nats:latest
    container_name: nats-1
    ports:
      - "4222:4222" # Client port
      - "8222:8222" # Monitoring port
      - "6222:6222" # Clustering port
    command: >
      -js
      -cluster_name nats
      -server_name nats-1
      -p 4222
      -m 8222
      -cluster nats://0.0.0.0:6222
      -routes nats://nats-2:6222,nats://nats-3:6222
    networks:
      - nats-network

  nats-2:
    image: nats:latest
    container_name: nats-2
    ports:
      - "4223:4222"
      - "8223:8222"
      - "6223:6222"
    command: >
      -js
      -cluster_name nats
      -server_name nats-2
      -p 4222
      -m 8222
      -cluster nats://0.0.0.0:6222
      -routes nats://nats-1:6222,nats://nats-3:6222
    networks:
      - nats-network

  nats-3:
    image: nats:latest
    container_name: nats-3
    ports:
      - "4224:4222"
      - "8224:8222"
      - "6224:6222"
    command: >
      -js
      -cluster_name nats
      -server_name nats-3
      -p 4222
      -m 8222
      -cluster nats://0.0.0.0:6222
      -routes nats://nats-1:6222,nats://nats-2:6222
    networks:
      - nats-network

  # Publisher (Message Sender)
  publisher:
    build:
      context: ./NatsDemo.Publisher
      dockerfile: Dockerfile
    container_name: nats-publisher
    depends_on:
      - nats-1
    networks:
      - nats-network
    environment:
      - NATS_URL=nats://nats-1:4222

  # Subscriber (Message Receiver)
  subscriber:
    build:
      context: ./NatsDemo.Subscriber
      dockerfile: Dockerfile
    container_name: nats-subscriber
    depends_on:
      - nats-1
    networks:
      - nats-network
    environment:
      - NATS_URL=nats://nats-1:4222

networks:
  nats-network:
    driver: bridge
